// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	dto "github.com/lasthearth/vsservice/internal/lfg/internal/dto"
	model "github.com/lasthearth/vsservice/internal/lfg/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
	"time"
)

type MapperImpl struct{}

func (c *MapperImpl) FromModel(source model.Post) dto.Post {
	var dtoPost dto.Post
	dtoPost.AuthorId = source.AuthorId
	dtoPost.Kind = string(source.Kind)
	if source.Activities != nil {
		dtoPost.Activities = make([]string, len(source.Activities))
		for i := 0; i < len(source.Activities); i++ {
			dtoPost.Activities[i] = string(source.Activities[i])
		}
	}
	dtoPost.Title = source.Title
	dtoPost.Description = source.Description
	dtoPost.StartsAt = c.pTimeTimeToPTimeTime(source.StartsAt)
	dtoPost.Slots = source.Slots
	if source.Responders != nil {
		dtoPost.Responders = make([]string, len(source.Responders))
		for j := 0; j < len(source.Responders); j++ {
			dtoPost.Responders[j] = source.Responders[j]
		}
	}
	if source.PlayDays != nil {
		dtoPost.PlayDays = make([]int32, len(source.PlayDays))
		for k := 0; k < len(source.PlayDays); k++ {
			dtoPost.PlayDays[k] = source.PlayDays[k]
		}
	}
	if source.PlayTimes != nil {
		dtoPost.PlayTimes = make([]string, len(source.PlayTimes))
		for l := 0; l < len(source.PlayTimes); l++ {
			dtoPost.PlayTimes[l] = string(source.PlayTimes[l])
		}
	}
	dtoPost.Experience = string(source.Experience)
	dtoPost.Voice = source.Voice
	dtoPost.Contact = source.Contact
	dtoPost.ClosedAt = c.pTimeTimeToPTimeTime(source.ClosedAt)
	dtoPost.ExpiresAt = goverter.TimeToTime(source.ExpiresAt)
	dtoPost.BumpedAt = goverter.TimeToTime(source.BumpedAt)
	return dtoPost
}
func (c *MapperImpl) ToModel(source dto.Post) model.Post {
	var modelPost model.Post
	modelPost.Id = goverter.ObjectIdToString(source.Model.Id)
	modelPost.AuthorId = source.AuthorId
	modelPost.Kind = model.Kind(source.Kind)
	if source.Activities != nil {
		modelPost.Activities = make([]model.Activity, len(source.Activities))
		for i := 0; i < len(source.Activities); i++ {
			modelPost.Activities[i] = model.Activity(source.Activities[i])
		}
	}
	modelPost.Title = source.Title
	modelPost.Description = source.Description
	modelPost.StartsAt = c.pTimeTimeToPTimeTime(source.StartsAt)
	modelPost.Slots = source.Slots
	if source.Responders != nil {
		modelPost.Responders = make([]string, len(source.Responders))
		for j := 0; j < len(source.Responders); j++ {
			modelPost.Responders[j] = source.Responders[j]
		}
	}
	if source.PlayDays != nil {
		modelPost.PlayDays = make([]int32, len(source.PlayDays))
		for k := 0; k < len(source.PlayDays); k++ {
			modelPost.PlayDays[k] = source.PlayDays[k]
		}
	}
	if source.PlayTimes != nil {
		modelPost.PlayTimes = make([]model.PlayTime, len(source.PlayTimes))
		for l := 0; l < len(source.PlayTimes); l++ {
			modelPost.PlayTimes[l] = model.PlayTime(source.PlayTimes[l])
		}
	}
	modelPost.Experience = model.Experience(source.Experience)
	modelPost.Voice = source.Voice
	modelPost.Contact = source.Contact
	modelPost.ClosedAt = c.pTimeTimeToPTimeTime(source.ClosedAt)
	modelPost.ExpiresAt = goverter.TimeToTime(source.ExpiresAt)
	modelPost.BumpedAt = goverter.TimeToTime(source.BumpedAt)
	modelPost.CreatedAt = goverter.TimeToTime(source.Model.CreatedAt)
	modelPost.UpdatedAt = goverter.TimeToTime(source.Model.UpdatedAt)
	return modelPost
}
func (c *MapperImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := goverter.TimeToTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
