// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/mail/v1"
	goverter "github.com/lasthearth/vsservice/internal/mail/internal/goverter"
	model "github.com/lasthearth/vsservice/internal/mail/internal/model"
	goverter1 "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) ToMailProto(source *model.Mail) *v1.Mail {
	var pMailv1Mail *v1.Mail
	if source != nil {
		var mailv1Mail v1.Mail
		mailv1Mail.Id = (*source).Id
		mailv1Mail.Recipient = (*source).Recipient
		mailv1Mail.Sender = (*source).Sender
		mailv1Mail.Title = (*source).Title
		mailv1Mail.Body = (*source).Body
		if (*source).Attachments != nil {
			mailv1Mail.Attachments = make([]*v1.Attachment, len((*source).Attachments))
			for i := 0; i < len((*source).Attachments); i++ {
				mailv1Mail.Attachments[i] = goverter.AttachmentModelToProto((*source).Attachments[i])
			}
		}
		mailv1Mail.CreatedAt = goverter1.TimeToTimestamp((*source).CreatedAt)
		mailv1Mail.ExpiresAt = goverter1.TimePtrToTimestamp((*source).ExpiresAt)
		mailv1Mail.Revoked = (*source).Revoked
		pMailv1Mail = &mailv1Mail
	}
	return pMailv1Mail
}
func (c *MapperImpl) ToMailsProto(source []*model.Mail) []*v1.Mail {
	var pMailv1MailList []*v1.Mail
	if source != nil {
		pMailv1MailList = make([]*v1.Mail, len(source))
		for i := 0; i < len(source); i++ {
			pMailv1MailList[i] = c.ToMailProto(source[i])
		}
	}
	return pMailv1MailList
}
