services:
  scalar:
    image: nginx:alpine
    container_name: "scalar-docs-container"
    ports:
      - "8888:80"
    volumes:
      - ./docs/scalar/index.html:/usr/share/nginx/html/index.html:ro
      - ./docs/v1/openapi.yaml:/usr/share/nginx/html/v1.openapi.yaml:ro
