services:
  vsservice:
    build:
      context: .
      target: final
    environment:
      GRPC_PORT: ${GRPC_PORT}
      GATEAWAY_PORT: ${GATEAWAY_PORT}
      VSAPI_URL: ${VSAPI_URL}
      MONGO_URL_FILE: ${MONGO_URL_FILE}
      STATS_FETCHING_INTERVAL_SECS: ${STATS_FETCHING_INTERVAL_SECS}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BASE_URL: ${DISCORD_BASE_URL:-https://discord.com/api/v10}
      DISCORD_NEWS_WEBHOOK_URL: ${DISCORD_NEWS_WEBHOOK_URL}
      DISCORD_ALLOWED_CHANNELS: ${DISCORD_ALLOWED_CHANNELS}
    volumes:
      - ./mongo/url.txt:/etc/vsservice/mongo/url.txt
    ports:
      - "50051:50051"
      - "6969:6969"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    ports:
      - "8080"
    volumes:
      - ./docs/v1/openapi.yaml:/v1.openapi.yaml
    environment:
      SWAGGER_JSON: /v1.openapi.yaml
      URLS: "[
        { url: 'v1.openapi.yaml', name: 'API Version 1.0'},
      ]"