services:
  vsservice:
    build:
      context: .
      target: final
    environment:
      GRPC_PORT: 50051
      GATEAWAY_PORT: 6969
      VSAPI_URL: http://vsservice:5000
      MONGO_URL_FILE: /etc/vsservice/mongo/url.txt
    volumes:
      - ./mongo/url.txt:/etc/vsservice/mongo/url.txt
    ports:
      - "50051:50051"
      - "6969:6969"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    ports:
      - "8080"
    volumes:
      - ./docs/v1/openapi.yaml:/v1.openapi.yaml
    environment:
      SWAGGER_JSON: /v1.openapi.yaml
      URLS: "[
        { url: 'v1.openapi.yaml', name: 'API Version 1.0'},
      ]"
