// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	dto "github.com/lasthearth/vsservice/internal/appearance/internal/dto"
	model "github.com/lasthearth/vsservice/internal/appearance/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) FromModel(source model.Appearance) dto.Appearance {
	var dtoAppearance dto.Appearance
	dtoAppearance.UserId = source.UserId
	dtoAppearance.BannerId = source.BannerId
	dtoAppearance.BannerEffect = source.BannerEffect
	dtoAppearance.FrameId = source.FrameId
	dtoAppearance.FrameEffect = source.FrameEffect
	dtoAppearance.TitleKey = source.TitleKey
	dtoAppearance.UpdatedAt = goverter.TimeToTime(source.UpdatedAt)
	return dtoAppearance
}
func (c *MapperImpl) ToModel(source dto.Appearance) model.Appearance {
	var modelAppearance model.Appearance
	modelAppearance.UserId = source.UserId
	modelAppearance.BannerId = source.BannerId
	modelAppearance.BannerEffect = source.BannerEffect
	modelAppearance.FrameId = source.FrameId
	modelAppearance.FrameEffect = source.FrameEffect
	modelAppearance.TitleKey = source.TitleKey
	modelAppearance.UpdatedAt = goverter.TimeToTime(source.UpdatedAt)
	return modelAppearance
}
func (c *MapperImpl) ToModels(source []dto.Appearance) []model.Appearance {
	var modelAppearanceList []model.Appearance
	if source != nil {
		modelAppearanceList = make([]model.Appearance, len(source))
		for i := 0; i < len(source); i++ {
			modelAppearanceList[i] = c.ToModel(source[i])
		}
	}
	return modelAppearanceList
}
