// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/event/v1"
	goverter1 "github.com/lasthearth/vsservice/internal/event/internal/goverter"
	model "github.com/lasthearth/vsservice/internal/event/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) CreateRequestToDetails(source *v1.CreateEventRequest) model.Details {
	var modelDetails model.Details
	if source != nil {
		modelDetails.Title = (*source).Title
		modelDetails.Description = (*source).Description
		modelDetails.Cover = (*source).Cover
		modelDetails.Location = (*source).Location
		modelDetails.StartsAt = goverter.TimestampToTime((*source).StartsAt)
		modelDetails.EndsAt = goverter1.TimestampToTimePtr((*source).EndsAt)
	}
	return modelDetails
}
func (c *MapperImpl) ToProto(source model.Event) *v1.Event {
	var eventv1Event v1.Event
	eventv1Event.Id = source.Id
	eventv1Event.Title = source.Title
	eventv1Event.Description = source.Description
	eventv1Event.Cover = source.Cover
	eventv1Event.Location = source.Location
	eventv1Event.StartsAt = goverter.TimeToTimestamp(source.StartsAt)
	eventv1Event.EndsAt = goverter.TimePtrToTimestamp(source.EndsAt)
	eventv1Event.CreatedBy = source.CreatedBy
	eventv1Event.CreatedAt = goverter.TimeToTimestamp(source.CreatedAt)
	eventv1Event.UpdatedAt = goverter.TimeToTimestamp(source.UpdatedAt)
	return &eventv1Event
}
func (c *MapperImpl) ToProtos(source []model.Event) []*v1.Event {
	var pEventv1EventList []*v1.Event
	if source != nil {
		pEventv1EventList = make([]*v1.Event, len(source))
		for i := 0; i < len(source); i++ {
			pEventv1EventList[i] = c.ToProto(source[i])
		}
	}
	return pEventv1EventList
}
func (c *MapperImpl) UpdateRequestToDetails(source *v1.UpdateEventRequest) model.Details {
	var modelDetails model.Details
	if source != nil {
		modelDetails.Title = (*source).Title
		modelDetails.Description = (*source).Description
		modelDetails.Cover = (*source).Cover
		modelDetails.Location = (*source).Location
		modelDetails.StartsAt = goverter.TimestampToTime((*source).StartsAt)
		modelDetails.EndsAt = goverter1.TimestampToTimePtr((*source).EndsAt)
	}
	return modelDetails
}
