// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/news/v1"
	model "github.com/lasthearth/vsservice/internal/news/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) ToProto(source model.News) *v1.News {
	var newsv1News v1.News
	newsv1News.Id = source.Id
	newsv1News.Title = source.Title
	newsv1News.Content = source.Content
	newsv1News.Preview = source.Preview
	newsv1News.ViewCount = source.ViewCount
	newsv1News.CreatedAt = goverter.TimeToTimestamp(source.CreatedAt)
	newsv1News.CreatedBy = source.CreatedBy
	return &newsv1News
}
func (c *MapperImpl) ToProtos(source []model.News) []*v1.News {
	var pNewsv1NewsList []*v1.News
	if source != nil {
		pNewsv1NewsList = make([]*v1.News, len(source))
		for i := 0; i < len(source); i++ {
			pNewsv1NewsList[i] = c.ToProto(source[i])
		}
	}
	return pNewsv1NewsList
}
