// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
	mongox "github.com/lasthearth/vsservice/internal/pkg/mongox"
	attachment "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/attachment"
	invitation "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/invitation"
	invitelink "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/invitelink"
	member "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/member"
	notifier "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/notifier"
	role "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/role"
	settlement "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/settlement"
	vector2 "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/vector2"
	verification "github.com/lasthearth/vsservice/internal/settlement/internal/dto/mongo/verification"
	model "github.com/lasthearth/vsservice/internal/settlement/model"
	"time"
)

type MapperImpl struct{}

func (c *MapperImpl) FromInvModel(source model.Invitation) invitation.Invitation {
	var invitationdtoInvitation invitation.Invitation
	invitationdtoInvitation.UserId = source.UserId
	invitationdtoInvitation.SettlementId = source.SettlementId
	return invitationdtoInvitation
}
func (c *MapperImpl) FromInvModels(source []model.Invitation) []invitation.Invitation {
	var invitationdtoInvitationList []invitation.Invitation
	if source != nil {
		invitationdtoInvitationList = make([]invitation.Invitation, len(source))
		for i := 0; i < len(source); i++ {
			invitationdtoInvitationList[i] = c.FromInvModel(source[i])
		}
	}
	return invitationdtoInvitationList
}
func (c *MapperImpl) FromInviteLinkModel(source model.InviteLink) invitelink.InviteLink {
	var invitelinkdtoInviteLink invitelink.InviteLink
	invitelinkdtoInviteLink.SettlementId = source.SettlementId
	invitelinkdtoInviteLink.Code = source.Code
	invitelinkdtoInviteLink.CreatedBy = source.CreatedBy
	invitelinkdtoInviteLink.MaxUses = source.MaxUses
	invitelinkdtoInviteLink.Uses = source.Uses
	invitelinkdtoInviteLink.ExpiresAt = c.pTimeTimeToPTimeTime(source.ExpiresAt)
	invitelinkdtoInviteLink.RevokedAt = c.pTimeTimeToPTimeTime(source.RevokedAt)
	return invitelinkdtoInviteLink
}
func (c *MapperImpl) FromSettlementDTO(source settlement.Settlement) model.Settlement {
	var modelSettlement model.Settlement
	modelSettlement.Id = goverter.ObjectIdToString(source.Model.Id)
	modelSettlement.Name = source.Name
	modelSettlement.Type = model.SettlementType(source.Type)
	modelSettlement.Description = source.Description
	modelSettlement.Leader = c.memberdtoMemberToModelMember(source.Leader)
	if source.Members != nil {
		modelSettlement.Members = make([]model.Member, len(source.Members))
		for i := 0; i < len(source.Members); i++ {
			modelSettlement.Members[i] = c.memberdtoMemberToModelMember(source.Members[i])
		}
	}
	modelSettlement.Coordinates = c.vector2dtoVector2ToModelVector2(source.Coordinates)
	modelSettlement.Diplomacy = source.Diplomacy
	if source.Attachments != nil {
		modelSettlement.Attachments = make([]model.Attachment, len(source.Attachments))
		for j := 0; j < len(source.Attachments); j++ {
			modelSettlement.Attachments[j] = c.attachmentdtoAttachmentToModelAttachment(source.Attachments[j])
		}
	}
	if source.TagIds != nil {
		modelSettlement.TagIds = make([]string, len(source.TagIds))
		for k := 0; k < len(source.TagIds); k++ {
			modelSettlement.TagIds[k] = source.TagIds[k]
		}
	}
	modelSettlement.ImperialFavor = source.ImperialFavor
	if source.Roles != nil {
		modelSettlement.Roles = make([]model.Role, len(source.Roles))
		for l := 0; l < len(source.Roles); l++ {
			modelSettlement.Roles[l] = c.roledtoRoleToModelRole(source.Roles[l])
		}
	}
	modelSettlement.RolesEnabled = source.RolesEnabled
	modelSettlement.ContactInfo = source.ContactInfo
	modelSettlement.NotifierReissues = source.NotifierReissues
	modelSettlement.UpdatedAt = goverter.TimeToTime(source.Model.UpdatedAt)
	modelSettlement.CreatedAt = goverter.TimeToTime(source.Model.CreatedAt)
	return modelSettlement
}
func (c *MapperImpl) FromSettlementsDTO(source []settlement.Settlement) []model.Settlement {
	var modelSettlementList []model.Settlement
	if source != nil {
		modelSettlementList = make([]model.Settlement, len(source))
		for i := 0; i < len(source); i++ {
			modelSettlementList[i] = c.FromSettlementDTO(source[i])
		}
	}
	return modelSettlementList
}
func (c *MapperImpl) FromVerification(source verification.SettlementVerification) settlement.Settlement {
	var settlementdtoSettlement settlement.Settlement
	settlementdtoSettlement.Model = c.mongoxModelToMongoxModel(source.Model)
	settlementdtoSettlement.Name = source.Name
	settlementdtoSettlement.Type = source.Type
	settlementdtoSettlement.Leader = c.memberdtoMemberToMemberdtoMember(source.Leader)
	settlementdtoSettlement.Coordinates = c.vector2dtoVector2ToVector2dtoVector2(source.Coordinates)
	if source.Attachments != nil {
		settlementdtoSettlement.Attachments = make([]attachment.Attachment, len(source.Attachments))
		for i := 0; i < len(source.Attachments); i++ {
			settlementdtoSettlement.Attachments[i] = c.attachmentdtoAttachmentToAttachmentdtoAttachment(source.Attachments[i])
		}
	}
	settlementdtoSettlement.Diplomacy = source.Diplomacy
	settlementdtoSettlement.Description = source.Description
	settlementdtoSettlement.NotifierReissues = source.NotifierReissues
	return settlementdtoSettlement
}
func (c *MapperImpl) ToInvModel(source invitation.Invitation) model.Invitation {
	var modelInvitation model.Invitation
	modelInvitation.Id = goverter.ObjectIdToString(source.Id)
	modelInvitation.UserId = source.UserId
	modelInvitation.SettlementId = source.SettlementId
	return modelInvitation
}
func (c *MapperImpl) ToInvModels(source []invitation.Invitation) []model.Invitation {
	var modelInvitationList []model.Invitation
	if source != nil {
		modelInvitationList = make([]model.Invitation, len(source))
		for i := 0; i < len(source); i++ {
			modelInvitationList[i] = c.ToInvModel(source[i])
		}
	}
	return modelInvitationList
}
func (c *MapperImpl) ToInviteLinkModel(source invitelink.InviteLink) model.InviteLink {
	var modelInviteLink model.InviteLink
	modelInviteLink.Id = goverter.ObjectIdToString(source.Model.Id)
	modelInviteLink.SettlementId = source.SettlementId
	modelInviteLink.Code = source.Code
	modelInviteLink.CreatedBy = source.CreatedBy
	modelInviteLink.MaxUses = source.MaxUses
	modelInviteLink.Uses = source.Uses
	modelInviteLink.ExpiresAt = c.pTimeTimeToPTimeTime(source.ExpiresAt)
	modelInviteLink.RevokedAt = c.pTimeTimeToPTimeTime(source.RevokedAt)
	modelInviteLink.CreatedAt = goverter.TimeToTime(source.Model.CreatedAt)
	modelInviteLink.UpdatedAt = goverter.TimeToTime(source.Model.UpdatedAt)
	return modelInviteLink
}
func (c *MapperImpl) ToInviteLinkModels(source []invitelink.InviteLink) []model.InviteLink {
	var modelInviteLinkList []model.InviteLink
	if source != nil {
		modelInviteLinkList = make([]model.InviteLink, len(source))
		for i := 0; i < len(source); i++ {
			modelInviteLinkList[i] = c.ToInviteLinkModel(source[i])
		}
	}
	return modelInviteLinkList
}
func (c *MapperImpl) ToNotifierPlacement(source notifier.Notifier) model.NotifierPlacement {
	var modelNotifierPlacement model.NotifierPlacement
	modelNotifierPlacement.SettlementId = source.SettlementId
	modelNotifierPlacement.Position = c.notifierdtoPositionToModelVector3(source.Position)
	modelNotifierPlacement.PlacedBy = source.PlacedBy
	modelNotifierPlacement.PlacedAt = goverter.TimeToTime(source.PlacedAt)
	return modelNotifierPlacement
}
func (c *MapperImpl) ToSettlementDTO(source model.Settlement) settlement.Settlement {
	var settlementdtoSettlement settlement.Settlement
	settlementdtoSettlement.Name = source.Name
	settlementdtoSettlement.Type = string(source.Type)
	settlementdtoSettlement.Leader = c.modelMemberToMemberdtoMember(source.Leader)
	if source.Members != nil {
		settlementdtoSettlement.Members = make([]member.Member, len(source.Members))
		for i := 0; i < len(source.Members); i++ {
			settlementdtoSettlement.Members[i] = c.modelMemberToMemberdtoMember(source.Members[i])
		}
	}
	settlementdtoSettlement.Coordinates = c.modelVector2ToVector2dtoVector2(source.Coordinates)
	if source.Attachments != nil {
		settlementdtoSettlement.Attachments = make([]attachment.Attachment, len(source.Attachments))
		for j := 0; j < len(source.Attachments); j++ {
			settlementdtoSettlement.Attachments[j] = c.modelAttachmentToAttachmentdtoAttachment(source.Attachments[j])
		}
	}
	settlementdtoSettlement.Diplomacy = source.Diplomacy
	settlementdtoSettlement.Description = source.Description
	if source.TagIds != nil {
		settlementdtoSettlement.TagIds = make([]string, len(source.TagIds))
		for k := 0; k < len(source.TagIds); k++ {
			settlementdtoSettlement.TagIds[k] = source.TagIds[k]
		}
	}
	settlementdtoSettlement.ImperialFavor = source.ImperialFavor
	if source.Roles != nil {
		settlementdtoSettlement.Roles = make([]role.Role, len(source.Roles))
		for l := 0; l < len(source.Roles); l++ {
			settlementdtoSettlement.Roles[l] = c.modelRoleToRoledtoRole(source.Roles[l])
		}
	}
	settlementdtoSettlement.RolesEnabled = source.RolesEnabled
	settlementdtoSettlement.ContactInfo = source.ContactInfo
	settlementdtoSettlement.NotifierReissues = source.NotifierReissues
	return settlementdtoSettlement
}
func (c *MapperImpl) attachmentdtoAttachmentToAttachmentdtoAttachment(source attachment.Attachment) attachment.Attachment {
	var attachmentdtoAttachment attachment.Attachment
	attachmentdtoAttachment.Url = source.Url
	attachmentdtoAttachment.Desc = source.Desc
	attachmentdtoAttachment.MimeType = source.MimeType
	return attachmentdtoAttachment
}
func (c *MapperImpl) attachmentdtoAttachmentToModelAttachment(source attachment.Attachment) model.Attachment {
	var modelAttachment model.Attachment
	modelAttachment.Url = source.Url
	modelAttachment.Desc = source.Desc
	modelAttachment.MimeType = source.MimeType
	return modelAttachment
}
func (c *MapperImpl) memberdtoMemberToMemberdtoMember(source member.Member) member.Member {
	var memberdtoMember member.Member
	memberdtoMember.UserId = source.UserId
	if source.RoleIds != nil {
		memberdtoMember.RoleIds = make([]string, len(source.RoleIds))
		for i := 0; i < len(source.RoleIds); i++ {
			memberdtoMember.RoleIds[i] = source.RoleIds[i]
		}
	}
	return memberdtoMember
}
func (c *MapperImpl) memberdtoMemberToModelMember(source member.Member) model.Member {
	var modelMember model.Member
	modelMember.UserId = source.UserId
	if source.RoleIds != nil {
		modelMember.RoleIds = make([]string, len(source.RoleIds))
		for i := 0; i < len(source.RoleIds); i++ {
			modelMember.RoleIds[i] = source.RoleIds[i]
		}
	}
	return modelMember
}
func (c *MapperImpl) modelAttachmentToAttachmentdtoAttachment(source model.Attachment) attachment.Attachment {
	var attachmentdtoAttachment attachment.Attachment
	attachmentdtoAttachment.Url = source.Url
	attachmentdtoAttachment.Desc = source.Desc
	attachmentdtoAttachment.MimeType = source.MimeType
	return attachmentdtoAttachment
}
func (c *MapperImpl) modelMemberToMemberdtoMember(source model.Member) member.Member {
	var memberdtoMember member.Member
	memberdtoMember.UserId = source.UserId
	if source.RoleIds != nil {
		memberdtoMember.RoleIds = make([]string, len(source.RoleIds))
		for i := 0; i < len(source.RoleIds); i++ {
			memberdtoMember.RoleIds[i] = source.RoleIds[i]
		}
	}
	return memberdtoMember
}
func (c *MapperImpl) modelRoleToRoledtoRole(source model.Role) role.Role {
	var roledtoRole role.Role
	roledtoRole.Id = source.Id
	roledtoRole.Name = source.Name
	if source.Permissions != nil {
		roledtoRole.Permissions = make([]string, len(source.Permissions))
		for i := 0; i < len(source.Permissions); i++ {
			roledtoRole.Permissions[i] = string(source.Permissions[i])
		}
	}
	return roledtoRole
}
func (c *MapperImpl) modelVector2ToVector2dtoVector2(source model.Vector2) vector2.Vector2 {
	var vector2dtoVector2 vector2.Vector2
	vector2dtoVector2.X = source.X
	vector2dtoVector2.Y = source.Y
	return vector2dtoVector2
}
func (c *MapperImpl) mongoxModelToMongoxModel(source mongox.Model) mongox.Model {
	var mongoxModel mongox.Model
	mongoxModel.Id = goverter.ObjectIdToObjectId(source.Id)
	mongoxModel.CreatedAt = goverter.TimeToTime(source.CreatedAt)
	mongoxModel.UpdatedAt = goverter.TimeToTime(source.UpdatedAt)
	mongoxModel.Version = source.Version
	return mongoxModel
}
func (c *MapperImpl) notifierdtoPositionToModelVector3(source notifier.Position) model.Vector3 {
	var modelVector3 model.Vector3
	modelVector3.X = source.X
	modelVector3.Y = source.Y
	modelVector3.Z = source.Z
	return modelVector3
}
func (c *MapperImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := goverter.TimeToTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
func (c *MapperImpl) roledtoRoleToModelRole(source role.Role) model.Role {
	var modelRole model.Role
	modelRole.Id = source.Id
	modelRole.Name = source.Name
	if source.Permissions != nil {
		modelRole.Permissions = make([]model.Permission, len(source.Permissions))
		for i := 0; i < len(source.Permissions); i++ {
			modelRole.Permissions[i] = model.Permission(source.Permissions[i])
		}
	}
	return modelRole
}
func (c *MapperImpl) vector2dtoVector2ToModelVector2(source vector2.Vector2) model.Vector2 {
	var modelVector2 model.Vector2
	modelVector2.X = source.X
	modelVector2.Y = source.Y
	return modelVector2
}
func (c *MapperImpl) vector2dtoVector2ToVector2dtoVector2(source vector2.Vector2) vector2.Vector2 {
	var vector2dtoVector2 vector2.Vector2
	vector2dtoVector2.X = source.X
	vector2dtoVector2.Y = source.Y
	return vector2dtoVector2
}
