// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/appearance/v1"
	model "github.com/lasthearth/vsservice/internal/appearance/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) RequestToChoice(source *v1.UpdateMyAppearanceRequest) model.Choice {
	var modelChoice model.Choice
	if source != nil {
		modelChoice.BannerId = (*source).BannerId
		modelChoice.BannerEffect = (*source).BannerEffect
		modelChoice.FrameId = (*source).FrameId
		modelChoice.FrameEffect = (*source).FrameEffect
		modelChoice.TitleKey = (*source).TitleKey
	}
	return modelChoice
}
func (c *MapperImpl) ToProto(source model.Appearance) *v1.Appearance {
	var appearancev1Appearance v1.Appearance
	appearancev1Appearance.UserId = source.UserId
	appearancev1Appearance.BannerId = source.BannerId
	appearancev1Appearance.BannerEffect = source.BannerEffect
	appearancev1Appearance.FrameId = source.FrameId
	appearancev1Appearance.FrameEffect = source.FrameEffect
	appearancev1Appearance.TitleKey = source.TitleKey
	appearancev1Appearance.UpdatedAt = goverter.TimeToTimestamp(source.UpdatedAt)
	return &appearancev1Appearance
}
func (c *MapperImpl) ToProtos(source []model.Appearance) []*v1.Appearance {
	var pAppearancev1AppearanceList []*v1.Appearance
	if source != nil {
		pAppearancev1AppearanceList = make([]*v1.Appearance, len(source))
		for i := 0; i < len(source); i++ {
			pAppearancev1AppearanceList[i] = c.ToProto(source[i])
		}
	}
	return pAppearancev1AppearanceList
}
