// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/lfg/v1"
	model "github.com/lasthearth/vsservice/internal/lfg/internal/model"
	service "github.com/lasthearth/vsservice/internal/lfg/internal/service"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) CreateRequestToDetails(source *v1.CreatePostRequest) model.Details {
	var modelDetails model.Details
	if source != nil {
		modelDetails.Kind = service.KindFromProto((*source).Kind)
		if (*source).Activities != nil {
			modelDetails.Activities = make([]model.Activity, len((*source).Activities))
			for i := 0; i < len((*source).Activities); i++ {
				modelDetails.Activities[i] = service.ActivityFromProto((*source).Activities[i])
			}
		}
		modelDetails.Title = (*source).Title
		modelDetails.Description = (*source).Description
		modelDetails.StartsAt = service.TimestampToTimePtr((*source).StartsAt)
		modelDetails.Slots = (*source).Slots
		if (*source).PlayDays != nil {
			modelDetails.PlayDays = make([]int32, len((*source).PlayDays))
			for j := 0; j < len((*source).PlayDays); j++ {
				modelDetails.PlayDays[j] = (*source).PlayDays[j]
			}
		}
		if (*source).PlayTimes != nil {
			modelDetails.PlayTimes = make([]model.PlayTime, len((*source).PlayTimes))
			for k := 0; k < len((*source).PlayTimes); k++ {
				modelDetails.PlayTimes[k] = service.PlayTimeFromProto((*source).PlayTimes[k])
			}
		}
		modelDetails.Experience = service.ExperienceFromProto((*source).Experience)
		modelDetails.Voice = (*source).Voice
		modelDetails.Contact = (*source).Contact
	}
	return modelDetails
}
func (c *MapperImpl) ToProto(source model.Post) *v1.Post {
	var lfgv1Post v1.Post
	lfgv1Post.Id = source.Id
	lfgv1Post.AuthorId = source.AuthorId
	lfgv1Post.Kind = service.KindToProto(source.Kind)
	if source.Activities != nil {
		lfgv1Post.Activities = make([]v1.Activity, len(source.Activities))
		for i := 0; i < len(source.Activities); i++ {
			lfgv1Post.Activities[i] = service.ActivityToProto(source.Activities[i])
		}
	}
	lfgv1Post.Title = source.Title
	lfgv1Post.Description = source.Description
	lfgv1Post.StartsAt = goverter.TimePtrToTimestamp(source.StartsAt)
	lfgv1Post.Slots = source.Slots
	if source.Responders != nil {
		lfgv1Post.Responders = make([]string, len(source.Responders))
		for j := 0; j < len(source.Responders); j++ {
			lfgv1Post.Responders[j] = source.Responders[j]
		}
	}
	lfgv1Post.Closed = service.IsClosed(source.ClosedAt)
	lfgv1Post.ExpiresAt = goverter.TimeToTimestamp(source.ExpiresAt)
	lfgv1Post.CreatedAt = goverter.TimeToTimestamp(source.CreatedAt)
	lfgv1Post.BumpedAt = goverter.TimeToTimestamp(source.BumpedAt)
	if source.PlayDays != nil {
		lfgv1Post.PlayDays = make([]int32, len(source.PlayDays))
		for k := 0; k < len(source.PlayDays); k++ {
			lfgv1Post.PlayDays[k] = source.PlayDays[k]
		}
	}
	if source.PlayTimes != nil {
		lfgv1Post.PlayTimes = make([]v1.PlayTime, len(source.PlayTimes))
		for l := 0; l < len(source.PlayTimes); l++ {
			lfgv1Post.PlayTimes[l] = service.PlayTimeToProto(source.PlayTimes[l])
		}
	}
	lfgv1Post.Experience = service.ExperienceToProto(source.Experience)
	lfgv1Post.Voice = source.Voice
	lfgv1Post.HasContact = service.HasContact(source.Contact)
	return &lfgv1Post
}
func (c *MapperImpl) ToProtos(source []model.Post) []*v1.Post {
	var pLfgv1PostList []*v1.Post
	if source != nil {
		pLfgv1PostList = make([]*v1.Post, len(source))
		for i := 0; i < len(source); i++ {
			pLfgv1PostList[i] = c.ToProto(source[i])
		}
	}
	return pLfgv1PostList
}
