// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/discord/v1"
	model "github.com/lasthearth/vsservice/internal/discord/internal/model"
)

type MapperImpl struct{}

func (c *MapperImpl) ToProtoImage(source model.Image) *v1.Image {
	var discordv1Image v1.Image
	discordv1Image.Url = source.Url
	discordv1Image.ProxyUrl = source.ProxyUrl
	discordv1Image.Alt = source.Alt
	discordv1Image.AuthorName = source.Author
	discordv1Image.Timestamp = source.Timestamp
	discordv1Image.Width = source.Width
	discordv1Image.Height = source.Height
	return &discordv1Image
}
func (c *MapperImpl) ToProtoImages(source []model.Image) []*v1.Image {
	var pDiscordv1ImageList []*v1.Image
	if source != nil {
		pDiscordv1ImageList = make([]*v1.Image, len(source))
		for i := 0; i < len(source); i++ {
			pDiscordv1ImageList[i] = c.ToProtoImage(source[i])
		}
	}
	return pDiscordv1ImageList
}
func (c *MapperImpl) ToProtoMessage(source model.Message) *v1.Message {
	var discordv1Message v1.Message
	discordv1Message.Content = source.Content
	discordv1Message.AuthorName = source.Author
	discordv1Message.Timestamp = source.Timestamp
	discordv1Message.Type = string(source.Type)
	return &discordv1Message
}
func (c *MapperImpl) ToProtoMessages(source []model.Message) []*v1.Message {
	var pDiscordv1MessageList []*v1.Message
	if source != nil {
		pDiscordv1MessageList = make([]*v1.Message, len(source))
		for i := 0; i < len(source); i++ {
			pDiscordv1MessageList[i] = c.ToProtoMessage(source[i])
		}
	}
	return pDiscordv1MessageList
}
