// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	mongo "github.com/lasthearth/vsservice/internal/kit/internal/dto/mongo"
	model "github.com/lasthearth/vsservice/internal/kit/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
	"time"
)

type MapperImpl struct{}

func (c *MapperImpl) FromAssignment(source model.KitAssignment) mongo.Assignment {
	var mongoAssignment mongo.Assignment
	mongoAssignment.UserId = source.UserId
	mongoAssignment.KitName = source.KitName
	mongoAssignment.Status = string(source.Status)
	mongoAssignment.UserGameName = source.UserGameName
	mongoAssignment.AssignedAt = goverter.TimeToTime(source.AssignedAt)
	mongoAssignment.DeliveredAt = c.pTimeTimeToPTimeTime(source.DeliveredAt)
	mongoAssignment.ClaimedAt = c.pTimeTimeToPTimeTime(source.ClaimedAt)
	mongoAssignment.AssignedBy = source.AssignedBy
	return mongoAssignment
}
func (c *MapperImpl) FromAssignments(source []model.KitAssignment) []mongo.Assignment {
	var mongoAssignmentList []mongo.Assignment
	if source != nil {
		mongoAssignmentList = make([]mongo.Assignment, len(source))
		for i := 0; i < len(source); i++ {
			mongoAssignmentList[i] = c.FromAssignment(source[i])
		}
	}
	return mongoAssignmentList
}
func (c *MapperImpl) ToAssignment(source mongo.Assignment) model.KitAssignment {
	var modelKitAssignment model.KitAssignment
	modelKitAssignment.Id = goverter.ObjectIdToString(source.Model.Id)
	modelKitAssignment.UserId = source.UserId
	modelKitAssignment.UserGameName = source.UserGameName
	modelKitAssignment.KitName = source.KitName
	modelKitAssignment.Status = model.AssignmentStatus(source.Status)
	modelKitAssignment.AssignedAt = goverter.TimeToTime(source.AssignedAt)
	modelKitAssignment.DeliveredAt = c.pTimeTimeToPTimeTime(source.DeliveredAt)
	modelKitAssignment.ClaimedAt = c.pTimeTimeToPTimeTime(source.ClaimedAt)
	modelKitAssignment.AssignedBy = source.AssignedBy
	return modelKitAssignment
}
func (c *MapperImpl) ToAssignments(source []mongo.Assignment) []model.KitAssignment {
	var modelKitAssignmentList []model.KitAssignment
	if source != nil {
		modelKitAssignmentList = make([]model.KitAssignment, len(source))
		for i := 0; i < len(source); i++ {
			modelKitAssignmentList[i] = c.ToAssignment(source[i])
		}
	}
	return modelKitAssignmentList
}
func (c *MapperImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := goverter.TimeToTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
