// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/settlement/v1"
	model "github.com/lasthearth/vsservice/internal/settlement-tag/internal/model"
	service "github.com/lasthearth/vsservice/internal/settlement-tag/internal/service"
	color "google.golang.org/genproto/googleapis/type/color"
)

type MapperImpl struct{}

func (c *MapperImpl) ColorToProto(source model.Color) *color.Color {
	var colorColor color.Color
	colorColor.Red = source.Red
	colorColor.Green = source.Green
	colorColor.Blue = source.Blue
	colorColor.Alpha = service.Float32ToFloatValue(source.Alpha)
	return &colorColor
}
func (c *MapperImpl) TagToProto(source model.Tag) *v1.SettlementTag {
	var settlementv1SettlementTag v1.SettlementTag
	settlementv1SettlementTag.Id = source.Id
	settlementv1SettlementTag.Name = source.Name
	settlementv1SettlementTag.Color = c.ColorToProto(source.Color)
	settlementv1SettlementTag.Description = source.Description
	return &settlementv1SettlementTag
}
func (c *MapperImpl) TagsToProto(source []model.Tag) []*v1.SettlementTag {
	var pSettlementv1SettlementTagList []*v1.SettlementTag
	if source != nil {
		pSettlementv1SettlementTagList = make([]*v1.SettlementTag, len(source))
		for i := 0; i < len(source); i++ {
			pSettlementv1SettlementTagList[i] = c.TagToProto(source[i])
		}
	}
	return pSettlementv1SettlementTagList
}
