// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
	dto "github.com/lasthearth/vsservice/internal/settlement-tag/internal/dto"
	model "github.com/lasthearth/vsservice/internal/settlement-tag/internal/model"
)

type MapperImpl struct{}

func (c *MapperImpl) FromTagDto(source dto.Tag) model.Tag {
	var modelTag model.Tag
	modelTag.Id = goverter.ObjectIdToString(source.Model.Id)
	modelTag.Name = source.Name
	modelTag.Color = c.dtoColorToModelColor(source.Color)
	modelTag.Description = source.Description
	modelTag.CreatedAt = goverter.TimeToTime(source.Model.CreatedAt)
	modelTag.UpdatedAt = goverter.TimeToTime(source.Model.UpdatedAt)
	modelTag.IsActive = source.IsActive
	return modelTag
}
func (c *MapperImpl) FromTagDtos(source []dto.Tag) []model.Tag {
	var modelTagList []model.Tag
	if source != nil {
		modelTagList = make([]model.Tag, len(source))
		for i := 0; i < len(source); i++ {
			modelTagList[i] = c.FromTagDto(source[i])
		}
	}
	return modelTagList
}
func (c *MapperImpl) ToTagDto(source model.Tag) dto.Tag {
	var dtoTag dto.Tag
	dtoTag.Name = source.Name
	dtoTag.Color = c.modelColorToDtoColor(source.Color)
	dtoTag.Description = source.Description
	dtoTag.IsActive = source.IsActive
	return dtoTag
}
func (c *MapperImpl) dtoColorToModelColor(source dto.Color) model.Color {
	var modelColor model.Color
	modelColor.Red = source.Red
	modelColor.Green = source.Green
	modelColor.Blue = source.Blue
	modelColor.Alpha = source.Alpha
	return modelColor
}
func (c *MapperImpl) modelColorToDtoColor(source model.Color) dto.Color {
	var dtoColor dto.Color
	dtoColor.Red = source.Red
	dtoColor.Green = source.Green
	dtoColor.Blue = source.Blue
	dtoColor.Alpha = source.Alpha
	return dtoColor
}
