// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/kit/v1"
	model "github.com/lasthearth/vsservice/internal/kit/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) ToAssignmentProto(source *model.KitAssignment) *v1.Assignment {
	var pKitv1Assignment *v1.Assignment
	if source != nil {
		var kitv1Assignment v1.Assignment
		kitv1Assignment.Id = (*source).Id
		kitv1Assignment.UserId = (*source).UserId
		kitv1Assignment.KitName = (*source).KitName
		kitv1Assignment.Status = string((*source).Status)
		kitv1Assignment.UserGameName = (*source).UserGameName
		kitv1Assignment.AssignedAt = goverter.TimeToTimestamp((*source).AssignedAt)
		kitv1Assignment.DeliveredAt = goverter.TimePtrToTimestamp((*source).DeliveredAt)
		kitv1Assignment.ClaimedAt = goverter.TimePtrToTimestamp((*source).ClaimedAt)
		pKitv1Assignment = &kitv1Assignment
	}
	return pKitv1Assignment
}
func (c *MapperImpl) ToAssignmentsProto(source []*model.KitAssignment) []*v1.Assignment {
	var pKitv1AssignmentList []*v1.Assignment
	if source != nil {
		pKitv1AssignmentList = make([]*v1.Assignment, len(source))
		for i := 0; i < len(source); i++ {
			pKitv1AssignmentList[i] = c.ToAssignmentProto(source[i])
		}
	}
	return pKitv1AssignmentList
}
