// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	dto "github.com/lasthearth/vsservice/internal/event/internal/dto"
	model "github.com/lasthearth/vsservice/internal/event/internal/model"
	goverter "github.com/lasthearth/vsservice/internal/pkg/goverter"
	"time"
)

type MapperImpl struct{}

func (c *MapperImpl) FromModel(source model.Event) dto.Event {
	var dtoEvent dto.Event
	dtoEvent.Title = source.Title
	dtoEvent.Description = source.Description
	dtoEvent.Cover = source.Cover
	dtoEvent.Location = source.Location
	dtoEvent.StartsAt = goverter.TimeToTime(source.StartsAt)
	dtoEvent.EndsAt = c.pTimeTimeToPTimeTime(source.EndsAt)
	dtoEvent.CreatedBy = source.CreatedBy
	return dtoEvent
}
func (c *MapperImpl) ToModel(source dto.Event) model.Event {
	var modelEvent model.Event
	modelEvent.Id = goverter.ObjectIdToString(source.Id())
	modelEvent.Title = source.Title
	modelEvent.Description = source.Description
	modelEvent.Cover = source.Cover
	modelEvent.Location = source.Location
	modelEvent.StartsAt = goverter.TimeToTime(source.StartsAt)
	modelEvent.EndsAt = c.pTimeTimeToPTimeTime(source.EndsAt)
	modelEvent.CreatedBy = source.CreatedBy
	modelEvent.CreatedAt = goverter.TimeToTime(source.Model.CreatedAt)
	modelEvent.UpdatedAt = goverter.TimeToTime(source.Model.UpdatedAt)
	return modelEvent
}
func (c *MapperImpl) ToModels(source []dto.Event) []model.Event {
	var modelEventList []model.Event
	if source != nil {
		modelEventList = make([]model.Event, len(source))
		for i := 0; i < len(source); i++ {
			modelEventList[i] = c.ToModel(source[i])
		}
	}
	return modelEventList
}
func (c *MapperImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := goverter.TimeToTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
