// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/user/v1"
	model "github.com/lasthearth/vsservice/internal/player/internal/model"
)

type MapperImpl struct{}

func (c *MapperImpl) ToUserProto(source model.Player) *v1.User {
	var userv1User v1.User
	userv1User.UserId = source.UserId
	userv1User.UserGameName = source.UserGameName
	userv1User.UserName = source.UserName
	userv1User.PreviousNickname = source.PreviousNickname
	return &userv1User
}
func (c *MapperImpl) ToUserProtos(source []model.Player) []*v1.User {
	var pUserv1UserList []*v1.User
	if source != nil {
		pUserv1UserList = make([]*v1.User, len(source))
		for i := 0; i < len(source); i++ {
			pUserv1UserList[i] = c.ToUserProto(source[i])
		}
	}
	return pUserv1UserList
}
