// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/user/v1"
	model "github.com/lasthearth/vsservice/internal/player/internal/model"
)

type MapperImpl struct{}

func (c *MapperImpl) ToImageProto(source *model.Avatar) *v1.User_Image {
	var pUserv1User_Image *v1.User_Image
	if source != nil {
		var userv1User_Image v1.User_Image
		userv1User_Image.Original = (*source).Original
		userv1User_Image.X96 = (*source).X96
		userv1User_Image.X48 = (*source).X48
		pUserv1User_Image = &userv1User_Image
	}
	return pUserv1User_Image
}
func (c *MapperImpl) ToUserProto(source model.Player) *v1.User {
	var userv1User v1.User
	userv1User.UserId = source.UserId
	userv1User.UserGameName = source.UserGameName
	userv1User.Avatar = c.ToImageProto(source.Avatar)
	userv1User.UserName = source.UserName
	userv1User.PreviousNickname = source.PreviousNickname
	userv1User.IsOnline = source.IsOnline
	return &userv1User
}
func (c *MapperImpl) ToUserProtos(source []model.Player) []*v1.User {
	var pUserv1UserList []*v1.User
	if source != nil {
		pUserv1UserList = make([]*v1.User, len(source))
		for i := 0; i < len(source); i++ {
			pUserv1UserList[i] = c.ToUserProto(source[i])
		}
	}
	return pUserv1UserList
}
