// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package repomapper

import (
	mongo "github.com/lasthearth/vsservice/internal/donate/internal/dto/mongo"
	model "github.com/lasthearth/vsservice/internal/donate/internal/model"
)

type MapperImpl struct{}

func (c *MapperImpl) WalletToDTO(source model.Wallet) mongo.Wallet {
	var dtoWallet mongo.Wallet
	dtoWallet.PlayerID = source.PlayerID
	dtoWallet.PlayerName = source.PlayerName
	dtoWallet.Coins = source.Coins
	return dtoWallet
}
