// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/donate/v1"
	goverter "github.com/lasthearth/vsservice/internal/donate/internal/goverter"
	model "github.com/lasthearth/vsservice/internal/donate/internal/model"
	goverter1 "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) ToPurchaseProto(source *model.Purchase) *v1.Purchase {
	var pDonatev1Purchase *v1.Purchase
	if source != nil {
		var donatev1Purchase v1.Purchase
		donatev1Purchase.Id = (*source).Id
		donatev1Purchase.PlayerId = (*source).PlayerID
		donatev1Purchase.PlayerName = (*source).PlayerName
		donatev1Purchase.ItemId = (*source).ItemID
		donatev1Purchase.ItemName = (*source).ItemName
		donatev1Purchase.PricePaid = (*source).PricePaid
		donatev1Purchase.Status = goverter.PurchaseStatusToString((*source).Status)
		donatev1Purchase.CreatedAt = goverter1.TimeToTimestamp((*source).CreatedAt)
		donatev1Purchase.RefundedAt = goverter1.TimePtrToTimestamp((*source).RefundedAt)
		donatev1Purchase.IssuedAt = goverter1.TimePtrToTimestamp((*source).IssuedAt)
		donatev1Purchase.IssuedBy = goverter.PtrStringToString((*source).IssuedBy)
		donatev1Purchase.BasePrice = (*source).BasePrice
		donatev1Purchase.DiscountPercent = (*source).DiscountPercent
		pDonatev1Purchase = &donatev1Purchase
	}
	return pDonatev1Purchase
}
func (c *MapperImpl) ToPurchasesProto(source []*model.Purchase) []*v1.Purchase {
	var pDonatev1PurchaseList []*v1.Purchase
	if source != nil {
		pDonatev1PurchaseList = make([]*v1.Purchase, len(source))
		for i := 0; i < len(source); i++ {
			pDonatev1PurchaseList[i] = c.ToPurchaseProto(source[i])
		}
	}
	return pDonatev1PurchaseList
}
func (c *MapperImpl) ToShopItemProto(source *model.ShopItem) *v1.ShopItem {
	var pDonatev1ShopItem *v1.ShopItem
	if source != nil {
		var donatev1ShopItem v1.ShopItem
		donatev1ShopItem.Id = (*source).Id
		donatev1ShopItem.Name = (*source).Name
		donatev1ShopItem.Description = (*source).Description
		donatev1ShopItem.ImageUrl = (*source).ImageURL
		donatev1ShopItem.Price = (*source).Price
		donatev1ShopItem.IsAvailable = (*source).IsAvailable
		donatev1ShopItem.CreatedAt = goverter1.TimeToTimestamp((*source).CreatedAt)
		donatev1ShopItem.UpdatedAt = goverter1.TimeToTimestamp((*source).UpdatedAt)
		donatev1ShopItem.Code = (*source).Code
		donatev1ShopItem.ItemType = goverter.ItemTypeModelToProto((*source).Type)
		if (*source).Entries != nil {
			donatev1ShopItem.Entries = make([]*v1.KitEntry, len((*source).Entries))
			for i := 0; i < len((*source).Entries); i++ {
				donatev1ShopItem.Entries[i] = goverter.KitEntryModelToProto((*source).Entries[i])
			}
		}
		donatev1ShopItem.HasDiscount = (*source).HasDiscount
		donatev1ShopItem.DiscountPercent = (*source).DiscountPercent
		donatev1ShopItem.EffectivePrice = goverter.ShopItemEffectivePrice(source)
		if (*source).Privileges != nil {
			donatev1ShopItem.Privileges = make([]*v1.Privilege, len((*source).Privileges))
			for j := 0; j < len((*source).Privileges); j++ {
				donatev1ShopItem.Privileges[j] = goverter.PrivilegeModelToProto((*source).Privileges[j])
			}
		}
		donatev1ShopItem.DiscountStartsAt = goverter1.TimePtrToTimestamp((*source).DiscountStartsAt)
		donatev1ShopItem.DiscountEndsAt = goverter1.TimePtrToTimestamp((*source).DiscountEndsAt)
		pDonatev1ShopItem = &donatev1ShopItem
	}
	return pDonatev1ShopItem
}
func (c *MapperImpl) ToShopItemsProto(source []*model.ShopItem) []*v1.ShopItem {
	var pDonatev1ShopItemList []*v1.ShopItem
	if source != nil {
		pDonatev1ShopItemList = make([]*v1.ShopItem, len(source))
		for i := 0; i < len(source); i++ {
			pDonatev1ShopItemList[i] = c.ToShopItemProto(source[i])
		}
	}
	return pDonatev1ShopItemList
}
func (c *MapperImpl) ToTransactionProto(source *model.Transaction) *v1.Transaction {
	var pDonatev1Transaction *v1.Transaction
	if source != nil {
		var donatev1Transaction v1.Transaction
		donatev1Transaction.Id = (*source).Id
		donatev1Transaction.PlayerId = (*source).PlayerID
		donatev1Transaction.Amount = (*source).Amount
		donatev1Transaction.Type = goverter.TxTypeToString((*source).Type)
		donatev1Transaction.Reason = (*source).Reason
		donatev1Transaction.PurchaseId = (*source).PurchaseID
		donatev1Transaction.CreatedAt = goverter1.TimeToTimestamp((*source).CreatedAt)
		pDonatev1Transaction = &donatev1Transaction
	}
	return pDonatev1Transaction
}
func (c *MapperImpl) ToTransactionsProto(source []*model.Transaction) []*v1.Transaction {
	var pDonatev1TransactionList []*v1.Transaction
	if source != nil {
		pDonatev1TransactionList = make([]*v1.Transaction, len(source))
		for i := 0; i < len(source); i++ {
			pDonatev1TransactionList[i] = c.ToTransactionProto(source[i])
		}
	}
	return pDonatev1TransactionList
}
func (c *MapperImpl) ToWalletBalanceProto(source *model.Wallet) *v1.WalletBalance {
	var pDonatev1WalletBalance *v1.WalletBalance
	if source != nil {
		var donatev1WalletBalance v1.WalletBalance
		donatev1WalletBalance.PlayerId = (*source).PlayerID
		donatev1WalletBalance.PlayerName = (*source).PlayerName
		donatev1WalletBalance.Coins = (*source).Coins
		pDonatev1WalletBalance = &donatev1WalletBalance
	}
	return pDonatev1WalletBalance
}
func (c *MapperImpl) ToWalletBalancesProto(source []*model.Wallet) []*v1.WalletBalance {
	var pDonatev1WalletBalanceList []*v1.WalletBalance
	if source != nil {
		pDonatev1WalletBalanceList = make([]*v1.WalletBalance, len(source))
		for i := 0; i < len(source); i++ {
			pDonatev1WalletBalanceList[i] = c.ToWalletBalanceProto(source[i])
		}
	}
	return pDonatev1WalletBalanceList
}
