name: Build and push app to registry

on:
  push:
    branches:
      - master
      - dev

env:
  DOCKER_REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set DOCKER_IMAGE env (append -dev for dev branch)
        run: |
          # DOCKER_REGISTRY доступна из env
          # If build in dev branch append suffix "-dev"
          if [ "${{ github.ref_name }}" = "dev" ]; then
            SUFFIX="-dev"
          else
            SUFFIX=""
          fi

          echo "TAG_SUFFIX=$SUFFIX" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=$DOCKER_REGISTRY/lasthearth/vsservice$SUFFIX" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to container registry
        uses: docker/login-action@v3
        id: login
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
