// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sermapper

import (
	v1 "github.com/lasthearth/vsservice/gen/kitdef/v1"
	goverter "github.com/lasthearth/vsservice/internal/kitdef/internal/goverter"
	model "github.com/lasthearth/vsservice/internal/kitdef/internal/model"
	goverter1 "github.com/lasthearth/vsservice/internal/pkg/goverter"
)

type MapperImpl struct{}

func (c *MapperImpl) ToKitDefProto(source *model.KitDef) *v1.KitDef {
	var pKitdefv1KitDef *v1.KitDef
	if source != nil {
		var kitdefv1KitDef v1.KitDef
		kitdefv1KitDef.Code = (*source).Code
		kitdefv1KitDef.Title = (*source).Title
		if (*source).Items != nil {
			kitdefv1KitDef.Items = make([]*v1.KitItem, len((*source).Items))
			for i := 0; i < len((*source).Items); i++ {
				kitdefv1KitDef.Items[i] = goverter.KitItemModelToProto((*source).Items[i])
			}
		}
		kitdefv1KitDef.CreatedAt = goverter1.TimeToTimestamp((*source).CreatedAt)
		kitdefv1KitDef.UpdatedAt = goverter1.TimeToTimestamp((*source).UpdatedAt)
		pKitdefv1KitDef = &kitdefv1KitDef
	}
	return pKitdefv1KitDef
}
func (c *MapperImpl) ToKitDefsProto(source []*model.KitDef) []*v1.KitDef {
	var pKitdefv1KitDefList []*v1.KitDef
	if source != nil {
		pKitdefv1KitDefList = make([]*v1.KitDef, len(source))
		for i := 0; i < len(source); i++ {
			pKitdefv1KitDefList[i] = c.ToKitDefProto(source[i])
		}
	}
	return pKitdefv1KitDefList
}
